/* This file was generated by configure.sh */
/* See MACSIMUS/generic/simopt.h for more details */
#define COOK
#define COULOMB 0
#define SLAB 1
#define NONBOND "lj"
#define WORM
#define LINKCELL 3
#define PARALLEL 1
#define BARRIER
#define VERLET 3
#define SHAKE 1
#define PROJECT "COOK-cutelst0-slab-lc-par1"
