# MACSIMUS key bindings (association of MACSIMUS file extensions with scripts
# and executables) for Midnight Commander 4.0.
#
# See file mc.ext for old Midnight Commander (version <4.8 or <4.0: I do
# not know the exact version when the Midnight Commander file format changed).
#
# Installation:
#   - Find file ~/.config/mc/mc.ext.ini
#   - Find line '######### Includes #########' in it
#   - Insert this file before the above line
#
# See also start and .startdata

# MACSIMUS che-file (input): process by helper che.sh
# CHE=0 che.sh NAME.che -> blend -g5 -r2 NAME.che
# CHE=1 che.sh NAME.che -> nmf.sh NAME.che
# CHE=2 che.sh NAME.che -> nmf4guest.sh NAME.che
[che]
Shell=.che
Open=che.sh %f 2>&1

# Show already calculated normal vibrational modes
[nmf]
Shell=.nmf
Open=shownmf.sh %f 2>&1

# MACSIMUS molecular topology file: process by blend
[mol]
Shell=.mol
Open=blend -g5 %f 2>&1

# Convergence profiles: show all of them using plot
[cp]
Shell=.cp
Open=showcp -p %f 2>&1

# Show the configuration
[cfg]
Shell=.cfg
Open=showcfg %f 2>&1

# Play the MACSIMUS playback file (.mol,.gol needed) in the ball mode
[plb]
Shell=.plb
Open=show -I%%i %f 2>&1

# As above (obsolete)
[gol]
Shell=.gol
Open=show -I%% %f &

# Print summary statistics (use Ctrl-O to view)
[sta]
Shell=.sta
Open=staprt -k %f
View=staprt %f

# Plot radial and cumulative distribution functions
[rdf]
Shell=.rdf
Open=rdfg %f -g -p 2>&1
View=rdfg %f -c -p 2>&1

# Show a single RDF and similar simple plots of common MACSIMUS data files
[plot]
Regex=\\.(g|cn|res|dat|sfr|sfg)$
Open=plot %f 2>&1

# Run simulation (using the 1st line of the file)
[run]
Regex=\\.(get|def)
Open=go %f

# Less common extensions

# Packed convergence profiles: show all of them using plot
[cpz]
Shell=.cpz
Open=showcp -p %f &

# Show the (already generated) ASCII image of .cp: Etot, T, Epot only
[cpa]
Shell=.cpa
Open=plotcpa %f

# raytrace and show (.nff can be saved by show)
[nff]
Shell=.nff
Open=ray -n %b -t -vdisplay

# stop a simulation running in the background
[loc]
Shell=.loc
Open=stop.sh %f

# PDB file: convert to MACSIMUS using charmm21.par (obsolete)
[pdb]
Shell=.pdb
Open=pdb -fcharmm21 %f

# show atom file, widely compatible (Gromacs, Gaussian, etc.)
[atm]
Shell=.atm
Open=showatm %f

# view residue
[rsd]
Shell=.rsd
Open=rsd %f

# show z-profiles (this interferes with old compression format .z)
[z-profile]
Shell=.z
Open=plot %f:1:2 :3 :4 :5 :6 :7 :8 :9
