/* This file was generated by configure.sh */
/* See MACSIMUS/generic/simopt.h for more details */
#define COOK
#define FREEBC
#define NONBOND "lj"
#define VERLET 3
#define SHAKE 1
#define PROJECT "COOK-free"
