/* This file was generated by configure.sh */
/* See MACSIMUS/generic/simopt.h for more details */
#define COOK
#define COULOMB -2
#define SPLINE -2
#define SLAB 1
#define NONBOND "lj"
#define WORM
#define LINKCELL 3
#define VERLET 3
#define SHAKE 1
#define PROJECT "COOK-Ewald-slab-lc"
